<a href="https://colab.research.google.com/github/ooeyad/Projects/blob/master/MOI_accidents_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from datetime import datetime as dt,timedelta
from matplotlib import pyplot as plt
from fbprophet import Prophet
import datetime
    
    
def fix_hour(time):
    time_parts = time.split(':')
    hour = int(time_parts[0])
    if hour == 0:
        time_parts[0] = '12'
    elif hour > 12:
        time_parts[0] = str(hour - 12)
    time_parts = ':'.join(time_parts)
    return time_parts

def get_time_shift(time):
    hour = time.hour
    if hour >= 0 and hour < 6:
        return 1
    elif hour >= 6 and hour < 12:
        return 2
    elif hour >= 12 and hour < 18:
        return 3
    else:
        return 4

In [0]:
df  = pd.read_csv('/acc_2019_2018.csv')
df

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning:

Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.

       AGI_ACCDATE  AGI_ACCTIME  AGI_TMETYP  ...  AGI_CLSCDE  AGI_XCOORD  AGI_YCOORD
0       2019-06-19  10:57:00 AM           1  ...          0    51.558727   25.241964
1       2019-06-20  10:46:00 AM           1  ...          0    51.558739   25.241816
2       2019-06-20   7:35:00 AM           2  ...          0    51.519810   25.297768
3       2019-06-21   5:39:00 AM           1  ...          1    51.464271   25.329807
4       2019-06-21  10:42:00 AM           1  ...          0    51.558728   25.242011
...            ...          ...         ...  ...         ...         ...         ...
530839  2019-10-27  11:00:00 AM           1  ...          0    51.547631   25.278093
530840  2019-10-27  11:00:00 AM           1  ...          0    51.459288   25.242264
530841  2019-10-27  10:00:00 AM           1  ...          0    51.386271   25.312024
530842  2019-10-26   9:30:00 AM           1  ...          0    51.544974   25.273435
530843  2019-10-27  11:15:00 AM           1  ...          0    51.464850   25.301354

[530844 rows x 21 columns]

In [0]:
df  = pd.read_csv('/content/acc2019_2018.csv')
df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.object).str.strip()
df['AGI_AREACDE'] = pd.to_numeric(df['AGI_AREACDE'], errors='coerce').fillna(0)
df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.int)
df = df[df['AGI_AREACDE'] > 0 ]

#no need for coordinates 
del df['AGI_XCOORD']
del df['AGI_YCOORD']

# fix hours to be between 1-12, and change the column to datetime with 24 hour format
df['AGI_ACCTIME'] = df['AGI_ACCTIME'].apply(fix_hour)
df['FULL_DATE'] = df['AGI_ACCDATE'] + ' ' + df['AGI_ACCTIME'] + ' ' + (np.where(df['AGI_TMETYP'] == 1 , 'AM' , 'PM'))
df['FULL_DATE'] = pd.to_datetime(df['FULL_DATE'],format = '%Y-%m-%d %I:%M:%S %p')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning:

Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.

In [0]:
df[df['']]

  AGI_ACCDATE AGI_ACCTIME  AGI_TMETYP  ...  AGI_RDTYP  AGI_CLSCDE           FULL_DATE
0  2019-06-19    10:57:00           1  ...          1          0  2019-06-19 10:57:00
1  2019-06-20    10:46:00           1  ...          1          0  2019-06-20 10:46:00
2  2019-06-20    07:35:00           2  ...          A          0  2019-06-20 19:35:00
3  2019-06-21    05:39:00           1  ...          1          1  2019-06-21 05:39:00
4  2019-06-21    10:42:00           1  ...          1          0  2019-06-21 10:42:00

[5 rows x 20 columns]

In [0]:
df[df['AGI_ACCTIME'].str.contains('PM') & ~df['AGI_ACCTIME'].str.contains('12')]

Empty DataFrame
Columns: [AGI_ACCDATE, AGI_ACCTIME, AGI_TMETYP, AGI_DPTCDE, AGI_ACCTYP, AGI_DISTNO, AGI_AREACDE, AGI_CITYCDE, AGI_STRTCDE, AGI_DTHCNT, AGI_CMPLXCNT, AGI_SMPLCNT, AGI_ACCNATR, AGI_RSNCDE, AGI_ACCCLS, AGI_WEATHER, AGI_ROAD, AGI_RDTYP, AGI_CLSCDE, FULL_DATE]
Index: []

In [0]:
if 1==1:
    
    from scipy.stats import boxcox
    from scipy.special import inv_boxcox
    
    
    #read the accidents files
    df  = pd.read_csv('/content/acc2019_2018.csv')


    # correct date and time columns
    df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.object).str.strip()
    df['AGI_AREACDE'] = pd.to_numeric(df['AGI_AREACDE'], errors='coerce').fillna(0)
    df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.int)
    df = df[df['AGI_AREACDE'] > 0 ]

    #no need for coordinates 
    del df['AGI_XCOORD']
    del df['AGI_YCOORD']

    # fix hours to be between 1-12, and change the column to datetime with 24 hour format
    df['AGI_ACCTIME'] = df['AGI_ACCTIME'].apply(fix_hour)
    df['FULL_DATE'] = df['AGI_ACCDATE'] + ' ' + df['AGI_ACCTIME'] + ' ' + (np.where(df['AGI_TMETYP'] == 1 , 'AM' , 'PM'))
    df['FULL_DATE'] = pd.to_datetime(df['FULL_DATE'],format = '%Y-%m-%d %I:%M:%S %p')

    # fix hours to be between 1-12, and change the column to datetime with 24 hour format
#     df['AGI_ACCTIME'] = df['AGI_ACCTIME'].apply(fix_hour)
#     df['FULL_DATE'] = df['AGI_ACCDATE'] + ' ' + df['AGI_ACCTIME'] + ' ' + (np.where(df['AGI_TMETYP'] == 1 , 'AM' , 'PM'))
#     df['FULL_DATE'] = pd.to_datetime(df['FULL_DATE'],format = '%m/%d/%Y %I:%M:%S %p')

#     df = pd.concat([df,df2019])

    df = df.sort_values('FULL_DATE').reset_index(drop = True)


    # create a time shift column
    df['TIME_SHIFT'] = df['FULL_DATE'].apply(get_time_shift)
    print(df[df.TIME_SHIFT > 1].tail(50))

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning:

Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.

       AGI_ACCDATE AGI_ACCTIME  ...           FULL_DATE  TIME_SHIFT
294842  2019-10-27    06:00:00  ... 2019-10-27 06:00:00           2
294843  2019-10-27    07:17:00  ... 2019-10-27 07:17:00           2
294844  2019-10-27    07:30:00  ... 2019-10-27 07:30:00           2
294845  2019-10-27    08:00:00  ... 2019-10-27 08:00:00           2
294846  2019-10-27    08:00:00  ... 2019-10-27 08:00:00           2
294847  2019-10-27    08:00:00  ... 2019-10-27 08:00:00           2
294848  2019-10-27    08:30:00  ... 2019-10-27 08:30:00           2
294849  2019-10-27    09:00:00  ... 2019-10-27 09:00:00           2
294850  2019-10-27    09:00:00  ... 2019-10-27 09:00:00           2
294851  2019-10-27    09:30:00  ... 2019-10-27 09:30:00           2
294852  2019-10-27    09:30:00  ... 2019-10-27 09:30:00           2
294853  2019-10-27    10:00:00  ... 2019-10-27 10:00:00           2
294854  2019-10-27    10:30:00  ... 2019-10-27 10:30:00           2
294855  2019-10-27    11:00:00  ... 2019-10-27 11:00:00           2
294856  2019-10-27    11:00:00  ... 2019-10-27 11:00:00           2
294857  2019-10-27    11:10:00  ... 2019-10-27 11:10:00           2
294858  2019-10-27    11:11:00  ... 2019-10-27 11:11:00           2
294859  2019-10-27    11:30:00  ... 2019-10-27 11:30:00           2
294860  2019-10-27    12:00:00  ... 2019-10-27 12:00:00           3
294861  2019-10-27    12:00:00  ... 2019-10-27 12:00:00           3
294862  2019-10-27    12:10:00  ... 2019-10-27 12:10:00           3
294863  2019-10-27    12:15:00  ... 2019-10-27 12:15:00           3
294864  2019-10-27    12:17:00  ... 2019-10-27 12:17:00           3
294865  2019-10-27    12:30:00  ... 2019-10-27 12:30:00           3
294866  2019-10-27    01:00:00  ... 2019-10-27 13:00:00           3
294867  2019-10-27    01:15:00  ... 2019-10-27 13:15:00           3
294868  2019-10-27    01:45:00  ... 2019-10-27 13:45:00           3
294869  2019-10-27    01:50:00  ... 2019-10-27 13:50:00           3
294870  2019-10-27    02:01:00  ... 2019-10-27 14:01:00           3
294871  2019-10-27    02:14:00  ... 2019-10-27 14:14:00           3
294872  2019-10-27    02:18:00  ... 2019-10-27 14:18:00           3
294873  2019-10-27    02:30:00  ... 2019-10-27 14:30:00           3
294874  2019-10-27    03:00:00  ... 2019-10-27 15:00:00           3
294875  2019-10-27    03:18:00  ... 2019-10-27 15:18:00           3
294876  2019-10-27    03:58:00  ... 2019-10-27 15:58:00           3
294877  2019-10-27    04:30:00  ... 2019-10-27 16:30:00           3
294878  2019-10-27    05:20:00  ... 2019-10-27 17:20:00           3
294879  2019-10-27    05:54:00  ... 2019-10-27 17:54:00           3
294880  2019-10-27    06:20:00  ... 2019-10-27 18:20:00           4
294881  2019-10-27    07:02:00  ... 2019-10-27 19:02:00           4
294882  2019-10-27    07:30:00  ... 2019-10-27 19:30:00           4
294883  2019-10-27    07:51:00  ... 2019-10-27 19:51:00           4
294884  2019-10-27    08:29:00  ... 2019-10-27 20:29:00           4
294885  2019-10-27    08:30:00  ... 2019-10-27 20:30:00           4
294886  2019-10-27    09:00:00  ... 2019-10-27 21:00:00           4
294887  2019-10-27    09:00:00  ... 2019-10-27 21:00:00           4
294888  2019-10-27    09:33:00  ... 2019-10-27 21:33:00           4
294889  2019-10-27    09:50:00  ... 2019-10-27 21:50:00           4
294890  2019-10-27    10:00:00  ... 2019-10-27 22:00:00           4
294891  2019-10-27    10:15:00  ... 2019-10-27 22:15:00           4

[50 rows x 21 columns]

In [0]:
def predict_for_area_shift2(area , shift,last_date):
    
    from scipy.stats import boxcox
    from scipy.special import inv_boxcox
    
    
    #read the accidents files
    df  = pd.read_csv('/content/acc2019_2018.csv')


    # correct date and time columns
    df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.object).str.strip()
    df['AGI_AREACDE'] = pd.to_numeric(df['AGI_AREACDE'], errors='coerce').fillna(0)
    df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.int)
    df = df[df['AGI_AREACDE'] > 0 ]

    #no need for coordinates 
    del df['AGI_XCOORD']
    del df['AGI_YCOORD']

    # fix hours to be between 1-12, and change the column to datetime with 24 hour format
    df['AGI_ACCTIME'] = df['AGI_ACCTIME'].apply(fix_hour)
    df['FULL_DATE'] = df['AGI_ACCDATE'] + ' ' + df['AGI_ACCTIME'] + ' ' + (np.where(df['AGI_TMETYP'] == 1 , 'AM' , 'PM'))
    df['FULL_DATE'] = pd.to_datetime(df['FULL_DATE'],format = '%Y-%m-%d %I:%M:%S %p')



    df = df.sort_values('FULL_DATE').reset_index(drop = True)


    # create a time shift column
    df['TIME_SHIFT'] = df['FULL_DATE'].apply(get_time_shift)

    #drop null area codes.
    df.drop(df[df.AGI_AREACDE.isna()].index, inplace=True)

    #sort by full_date
    df = df.sort_values('FULL_DATE')
    
    df_area57_ts = df[(df['AGI_AREACDE']==area) & (df['TIME_SHIFT']==shift)]
    
      
    df_area57_ts['NO_OF_ACCIDENTS'] = np.zeros(len(df_area57_ts['FULL_DATE']))
    df_area57_ts = df_area57_ts[['FULL_DATE','NO_OF_ACCIDENTS']].set_index('FULL_DATE').groupby(pd.Grouper(freq='D')).count().reset_index()
#     df_area57_ts = df_area57_ts[df_area57_ts['NO_OF_ACCIDENTS'] > 0]
    df_area57_ts = df_area57_ts.sort_values('FULL_DATE')
    df_area57_ts2 = df_area57_ts[(df_area57_ts['FULL_DATE'] >= '2018-01-01') & (df_area57_ts['FULL_DATE'] <= '2019-10-26')]
    
    # fill missing dates
    r = pd.date_range(start=df_area57_ts2.FULL_DATE.min(), end=df_area57_ts2.FULL_DATE.max())
    df_area57_ts2 = df_area57_ts2.set_index('FULL_DATE').reindex(r).fillna(0.0).rename_axis('FULL_DATE').reset_index()
    
    return df_area57_ts2

In [0]:
from_date = datetime.date(2019, 7, 1)
to_date = datetime.date(2019, 10, 1)
areas = [57,56,55]
df = predict_for_area_shift2(57 , 4,from_date)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning:

Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:43: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [0]:
df.tail()

     FULL_DATE  NO_OF_ACCIDENTS
653 2019-10-16                0
654 2019-10-17                0
655 2019-10-18                0
656 2019-10-19                0
657 2019-10-20                1

In [0]:
def predict_for_area_shift(area , shift,last_date):
    
    from scipy.stats import boxcox
    from scipy.special import inv_boxcox
    
    
    #read the accidents files
    df  = pd.read_csv('/content/acc2019_2018.csv')


    # correct date and time columns
    df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.object).str.strip()
    df['AGI_AREACDE'] = pd.to_numeric(df['AGI_AREACDE'], errors='coerce').fillna(0)
    df['AGI_AREACDE'] = df['AGI_AREACDE'].astype(np.int)
    df = df[df['AGI_AREACDE'] > 0 ]

    #no need for coordinates 
    del df['AGI_XCOORD']
    del df['AGI_YCOORD']

    # fix hours to be between 1-12, and change the column to datetime with 24 hour format
    df['AGI_ACCTIME'] = df['AGI_ACCTIME'].apply(fix_hour)
    df['FULL_DATE'] = df['AGI_ACCDATE'] + ' ' + df['AGI_ACCTIME'] + ' ' + (np.where(df['AGI_TMETYP'] == 1 , 'AM' , 'PM'))
    df['FULL_DATE'] = pd.to_datetime(df['FULL_DATE'],format = '%Y-%m-%d %I:%M:%S %p')

    # fix hours to be between 1-12, and change the column to datetime with 24 hour format
#     df['AGI_ACCTIME'] = df['AGI_ACCTIME'].apply(fix_hour)
#     df['FULL_DATE'] = df['AGI_ACCDATE'] + ' ' + df['AGI_ACCTIME'] + ' ' + (np.where(df['AGI_TMETYP'] == 1 , 'AM' , 'PM'))
#     df['FULL_DATE'] = pd.to_datetime(df['FULL_DATE'],format = '%m/%d/%Y %I:%M:%S %p')

#     df = pd.concat([df,df2019])

    df = df.sort_values('FULL_DATE').reset_index(drop = True)


    # create a time shift column
    df['TIME_SHIFT'] = df['FULL_DATE'].apply(get_time_shift)

    #drop null area codes.
    df.drop(df[df.AGI_AREACDE.isna()].index, inplace=True)

    #sort by full_date
    df = df.sort_values('FULL_DATE')
    df.to_csv('/content/sorted_df.csv')
    from scipy.stats import boxcox
    from scipy.special import inv_boxcox

    if shift == 0:
      df_area57_ts = df[df['AGI_AREACDE']==area]
    else:
      df_area57_ts = df[(df['AGI_AREACDE']==area) & (df['TIME_SHIFT']==shift)]
    df_area57_ts['NO_OF_ACCIDENTS'] = np.zeros(len(df_area57_ts['FULL_DATE']))
    df_area57_ts = df_area57_ts[['FULL_DATE','NO_OF_ACCIDENTS']].set_index('FULL_DATE').groupby(pd.Grouper(freq='D')).count().reset_index()
    df_area57_ts = df_area57_ts[df_area57_ts['NO_OF_ACCIDENTS'] > 0]
    df_area57_ts = df_area57_ts.sort_values('FULL_DATE')
    df_area57_ts2 = df_area57_ts[(df_area57_ts['FULL_DATE'] >= '2018-01-01') & (df_area57_ts['FULL_DATE'] <= '2019-10-26')]
    
    avg = np.mean(df_area57_ts2['NO_OF_ACCIDENTS'])
    
    # fill missing dates
    r = pd.date_range(start=df_area57_ts2.FULL_DATE.min(), end=df_area57_ts2.FULL_DATE.max())
    
    df_area57_ts2 = df_area57_ts2.set_index('FULL_DATE').reindex(r).fillna(avg).rename_axis('FULL_DATE').reset_index()
    
#     df_area57_ts2 = df_area57_ts2.set_index('FULL_DATE')
#     df_area57_ts2 = df_area57_ts2.reset_index()
    
    df_orig = df_area57_ts2.copy()
    df_area57_ts2 = df_area57_ts2[df_area57_ts2['FULL_DATE'] < last_date]
    
    national_day = pd.DataFrame({'holiday': 'national','ds': pd.to_datetime(['2018-12-18','2017-12-18','2016-12-18','2015-12-18']),'lower_window': 0,'upper_window': 10,})
    df_area57_ts2 = df_area57_ts2.rename(columns={'FULL_DATE': 'ds', 'NO_OF_ACCIDENTS': 'y'})
    
    df_area57_ts2['y'] = np.log(df_area57_ts2['y'])
                                
    #transform data using boxcox
#     a = []
#     avg = np.mean(df_area57_ts2['y'])
#     for i in range(len(df_area57_ts2['y'])):
#       if df_area57_ts2['y'][i] == 0:
#         a.append(0)
#       else:
#         a.append(np.log(df_area57_ts2['y'][i]))
#     df_area57_ts2['y'] = a
#     df_area57_ts2['y'], lam = boxcox(df_area57_ts2['y'])
    
    m = Prophet(weekly_seasonality=True)
#     m.add_seasonality(name='weekly', period=7, fourier_order=3, prior_scale=0.1)
#     m.add_seasonality(name="monthly", period=30.5, fourier_order=5, prior_scale=0.02)
    
    m.fit(df_area57_ts2)
    
    future = m.make_future_dataframe(periods=60)
#     df_area57_ts2.to_csv('/content/final_df{}_{}.csv'.format(area,shift))
    forecast = m.predict(future)
    
    #m.plot_components(forecast);
    
    forecast[['yhat','yhat_upper','yhat_lower']] = forecast[['yhat','yhat_upper','yhat_lower']].apply(lambda x: np.exp(x))
#     forecast[['yhat','yhat_upper','yhat_lower']] = forecast[['yhat','yhat_upper','yhat_lower']].apply(lambda x: inv_boxcox(x, lam))
    forecast[['yhat','yhat_upper','yhat_lower']] = forecast[['yhat','yhat_upper','yhat_lower']].apply(lambda x: np.round(x))
    return df_orig,forecast

#get_predictions receives list of areas
def get_predictions(areas,from_date,to_date):

  df_result = pd.DataFrame(columns = ['ACC_DATE','NO_OF_ACCIDENTS'])

  for a_area in areas:
    for a_shift in range(1,5):    
      ret_actual , acc_forecast = predict_for_area_shift(a_area , a_shift,from_date)
      if a_shift == 0:
        col_str = 'area_%s'%str(a_area)
      else:
        col_str = 'area_%s_shift%s'%(str(a_area),str(a_shift))
      if df_result['ACC_DATE'].count() == 0:
        df_result['ACC_DATE'] = acc_forecast['ds']
        df_result[col_str] = acc_forecast['yhat']
      else:
        df_result[col_str] = acc_forecast['yhat']
  df_result = df_result[(df_result['ACC_DATE'] >= from_date) & (df_result['ACC_DATE'] < to_date) ]
  del df_result['NO_OF_ACCIDENTS']
  print('Shifts : ----------------------')
  print('Shift1 : 0 - 6am')
  print('Shift2 : 6am - 12pm')
  print('Shift3 : 12pm - 6pm')
  print('Shift4 : 6pm - 0')
  
  return df_result

In [0]:
from_date = datetime.date(2019, 10, 25)
to_date = datetime.date(2019, 11, 10)
areas = [57,56,55]

df = get_predictions(areas,from_date,to_date)
df.to_csv('/content/predictions.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning:

Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:52: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:69: FutureWarning:

Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and a TypeError will be raised. To retain the current
behavior, convert the 'datetime.date' to a datetime with
'pd.Timestamp'.

INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

Shifts : ----------------------
Shift1 : 0 - 6am
Shift2 : 6am - 12pm
Shift3 : 12pm - 6pm
Shift4 : 6pm - 0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:121: FutureWarning:

Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and a TypeError will be raised. To retain the current
behavior, convert the 'datetime.date' to a datetime with
'pd.Timestamp'.

In [0]:
df_test = pd.read_csv('/content/final_df57_3.csv')

In [0]:
print(df_test)

     Unnamed: 0          ds         y
0             0  2018-10-01  2.027306
1             1  2018-10-02  1.516966
2             2  2018-10-03  0.675607
3             3  2018-10-04  1.811828
4             4  2018-10-05  0.000000
..          ...         ...       ...
324         324  2019-10-14  0.000000
325         325  2019-10-17  1.054985
326         326  2019-10-19  2.116453
327         327  2019-10-20  1.677655
328         328  2019-10-21  0.000000

[329 rows x 3 columns]